version: "3.9"
services:
  backend:
    container_name: chat-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "32530:8082"
    depends_on:
     # - "websocket"
      - "mongodb"
    restart: always
    environment:
      - GO_PORT=8082
      - ROOT_PATH=/app
    volumes:
      - ./:/app
    networks:
      - chat-network

  mongodb:
    container_name: chat-mdb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "32531:27017"
    restart: unless-stopped
    volumes:
      - ./docker/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./storage/db/mdb:/data/db
    networks:
      - chat-network
        
networks:
  chat-network:
    external: true